version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: banking_db_pg
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - /root/task/data/pgdata:/var/lib/postgresql/data
      - /root/task/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
    environment:
      POSTGRES_DB: banking_db
      POSTGRES_USER: bank_app_user
      POSTGRES_PASSWORD: bank_secret_pw
    networks:
      - banking_network
networks:
  banking_network:
    driver: bridge